Adding a control flow to remove approval label from PRs when reviews are dismissed.
ellevation/label-when-approved-action pull request #1
Opened 2021-05-27 21:00 UTC by ben-ellevation

2021-05-27 21:02 UTC, ben-ellevation commented on entrypoint.sh
> +elif [[ "$action" == "dismissed" ]]; then
I _think_ this is the correct combination of sorcerous action/state, but I think the worst case scenario is it doesn't fire.

Reference:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review

2021-05-27 21:04 UTC, ben-ellevation commented on entrypoint.sh
>  if [[ "$action" == "submitted" ]] && [[ "$state" == "approved" ]]; then
I'm a little annoyed that I couldn't find anything for state in the docs. :|

2021-05-27 21:05 UTC, justin-ellevation approved these changes

2021-05-27 21:05 UTC, ben-ellevation commented on entrypoint.sh
> +label_when_disapproved() {
Most of this is copy/pasta, except for the `lt` if statement and swapping out the labels to add/remove.

2021-05-28 01:38 UTC, andy-ellevation requested changes
your swapping of the labels makes the $REMOVE_LABEL a required parameter, where it wasn't before.

2021-05-28 01:38 UTC, andy-ellevation commented on entrypoint.sh
> +      if [[ -n "$addLabel" ]]; then
I don't think you need this if statement. in the other code, this was checking to see if $REMOVE_LABEL was defined before deleting the label. i think you should put this one outside the block, and then use the same -n check on $REMOVE_LABEL before trying to add it. alternately, you could require $REMOVE_LABEL in the initiation above, using a check like at line 20.

2021-05-28 01:38 UTC, andy-ellevation commented on entrypoint.sh
>  if [[ "$action" == "submitted" ]] && [[ "$state" == "approved" ]]; then
there's some here in the 'event' property: https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request
and if you search in the example responses, you can see state examples.

2021-05-28 01:38 UTC, andy-ellevation commented on entrypoint.sh
> +elif [[ "$action" == "dismissed" ]]; then
You could consider running the add and delete within the same event: if there are at least $APPROVALS approved reviews, then add the label. if there are less, then remove it. you'd still want to fire on the dismissed action.

you could also consider firing on https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
and use at least these actions:
ready_for_review
reopened
review_request_removed
review_requested

2021-05-28 14:24 UTC, ben-ellevation commented on entrypoint.sh
> +elif [[ "$action" == "dismissed" ]]; then
5 PM Ben was originally going for least ~amount of effort~ chances of disrupting the current behavior, but yeah, I'll DRY this up a bit. No reason I can't just call the same function.

2021-05-28 14:47 UTC, ben-ellevation commented
Oh yeesh wait a sec I think I confused myself on the code. One sec. (I thought I removed a function but apparently I just didn't?)

2021-05-28 14:48 UTC, ben-ellevation commented
Okay all good!

2021-05-28 14:50 UTC, ben-ellevation commented on entrypoint.sh
> +    label_to_remove = $REMOVE_LABEL
I figured shell has ACTUAL SCOPING unlike Python, but if it's Python scoping then I can move those into the if block below. Could also set these to a NULL if preferred?

2021-05-28 14:51 UTC, ben-ellevation commented on entrypoint.sh
> +elif ( [[ "$action" == "submitted" ]] || [[ "$action" == "dismissed" ]] ) && ( [[ "$state" == "DISMISSED" ]] || [[ "$state" == "CHANGES_REQUESTED" ]] ); then
I opted to leave these branches separate for readability but I don't feel too strongly about this.

2021-05-28 14:51 UTC, ben-ellevation commented on entrypoint.sh
> +# ADD_LABEL: The label that will be add when the PR is approved (and the label that will be removed when the PR lacks approvals)
I could rename these for clarity but I'd rather not change the interface right now.

2021-05-28 14:57 UTC, ben-ellevation commented on entrypoint.sh
> +      "${URI}/repos/${GITHUB_REPOSITORY}/issues/${number}/labels"
Also assuming adding a label that already exists or removing a label that doesn't exist doesn't cause a catastrophic failure on GitHub. >.>

2021-05-28 15:43 UTC, andy-ellevation approved these changes

2021-05-28 15:43 UTC, andy-ellevation commented on entrypoint.sh
> +      "${URI}/repos/${GITHUB_REPOSITORY}/issues/${number}/labels"
we'll find out!

2021-05-28 15:43 UTC, andy-ellevation commented on entrypoint.sh
> +    label_to_remove = $REMOVE_LABEL
i think it does not have actual scoping, last i checked. also, there's a convention that variables are ALL CAPS.

2021-05-28 15:43 UTC, andy-ellevation commented on entrypoint.sh
> +elif ( [[ "$action" == "submitted" ]] || [[ "$action" == "dismissed" ]] ) && ( [[ "$state" == "DISMISSED" ]] || [[ "$state" == "CHANGES_REQUESTED" ]] ); then
i like them being separate here. parsing actions is potentially annoying.

2021-05-28 15:50 UTC, alla-ellevation approved these changes

2021-05-28 16:05 UTC, merged